@selenium
Feature: Creating Purchase Order.
  Document generated by a user department or storeroom-personnel to notify the purchasing department of items it needs to order, their quantity, and the timeframe. It may also contain the authorization to proceed with the purchase. Also called purchase request or requisition.

  Background:
    Given I am authorized user
    When Go to admin PRN form screen in inventories.

  Scenario: Select store
    Given I able to see store information within store-list
      | field       | content               | content_holder |
      | name        | store1                | #store_name_2  |
      | description | This is sample store  | #store_desc_2  |
    And I click link store1
    And I able to see prn form with dom element new_inventory_prn
    And I enter inventory_prn required_at like 2016-09-20
    And I enter inventory_prn remarks like This is sample remarks
    And I click link Add Item
    And I able to see model with dom element modal_for_main_part