# In spt_ticket table, priority column
priority:
  Highest: 1
  High: 2
  Normal: 3
  Low: 4
  Lowest: 5

ticket_no_format: "T0000"

answer_type_for_q_and_a:
  "yes/no" : "YN"
  text: TX

pagination:
  customer_per_page: 2
  organization_per_page: 2