Organization:
  View organizations:
    actions:
      - index
      - show
    system_module:
      name: Organization

  Modify organization:
    actions:
      - new
      - edit
      - update
      - destroy
      - temp_save_user_profile_image
      - relate
      - demote_as_department
      - remove_department_org
      - option_for_vat_number
      - pin_relation
    system_module:
      name: Organization

  Re-Index access of all information:
    actions:
      - reindex_all_model

  Access and Modify Owner Organization:
    actions:
      - new
      - edit
      - update
      - destroy
    attributes:
      -
        name: refers
        value: CRM_OWNER

  # View parent organization:
  #   actions:
  #     - asdf
  # Modify parent organization:
  #   actions:
  #     - asdf
  Assign dealer type:
    actions:
      - dealer_types
    attributes:
      []
    system_module:
      name: Organization

  Modify customer contact details:
    actions:
      - inline_customer_contact_detail
    attributes:
      []
    system_module:
      name: Contract

  Access customer product:
    actions:
      - customer_search
    system_module:
      name: Organization

  Add/Edit customer contract:
    actions:
      - save
    system_module:
      name: Contract

  view customer contract:
    actions:
      - view
    system_module:
      name: Contract

  Create GRN:
    actions:
      - grn
      - upload_grn_file
      - initiate_grn_for_i_product
      - initialize_grn
      - initiate_grn_for_srr
      - create_grn
      - search_grn

  Update GRN Cost:
    actions:
      - update_grn_cost
    system_module:
      name: Inventory

  View part of main cost:
    actions:
      - create_grn_for_main_part
    system_module:
      name: Inventory

  Create GRN main part:
    actions:
      - grn_main_part
      - create_grn_for_main_part
    system_module:
      name: Inventory

  Create SRN:
    actions:
      - srn
      - create_srn
    system_module:
      name: Inventory

  Close SRN:
    actions:
      - close_srn
    system_module:
      name: Inventory

  Create SRR:
    actions:
      - srr
      - create_srr
    system_module:
      name: Inventory

  Create GIN:
    actions:
      - gin
      - gins
      - create_gin
    system_module:
      name: Inventory

  Create PO:
    actions:
      - po
      - pos
      - create_po
    system_module:
      name: Inventory
  Close PO:
    actions:
      - close_po
    system_module:
      name: Inventory

  Create PRN:
    actions:
      - prn
      - prns
      - create_prn
      - view_prn
    system_module:
      name: Inventory

  Close PRN:
    actions:
      - close_prn
    system_module:
      name: Inventory

  Access admin stores and branches:
    actions:
      - store_and_branch
    system_module:
      name: Organization

ProductSoldCountry:
  Access admin country information:
    actions:
      - country
      - delete_admin_country
    system_module:
      name: Organization

RegionalSupportCenter:
  Access admin regional information:
    actions:
      - regional_support_center
      - delete_admin_regional_support_center
    system_module:
      name: Organization

SlaTime:
  Access admin SLA information:
    actions:
      - sla
      - delete_admin_sla
    system_module:
      name: Organization

  Access admin permission information:
    system_module:
      name: Organization

IndustryType:
  Access admin industry type information:
    actions:
      - industry_type
      - delete_admin_industry_type
    attributes:
      []
    system_module:
      name: Organization

Sbu:
  Access admin sbu information:
    actions:
      - sbu
      - delete_admin_sbu
      - delete_admin_sbu_engineer
    attributes:
      []
    system_module:
      name: Organization

MstTitle:
  Access admin mst_title information:
    actions:
      - title
      - delete_admin_title
    system_module:
      name: Organization

SparePartDescription:
  Access admin spare part information:
    actions:
      - spare_part_description
    system_module:
      name: Ticket
  Access Brand & Category information:
    actions:
      - brands_and_category
      - delete_admin_brands_and_category
    system_module:
      name: Ticket

Reason:
  Access admin reason information:
    actions:
      - reason
      - delete_admin_inventory_reason
    system_module:
      name: Organization

Accessory:
  Access admin accessory information:
    actions:
      - accessories
      - delete_admin_accessory
    system_module:
      name: Ticket

GeQAndA:
  Access admin general question information:
    actions:
      - general_question
      - delete_admin_general_question
    system_module:
      name: Ticket

Feedback:
  Access admin customer feedback information:
    actions:
      - customer_feedback
      - delete_admin_customer_feedback
    system_module:
      name: Ticket

TicketStartAction:
  Access admin ticket start action information:
    actions:
      - start_action
      - delete_admin_ticket_start_action
    system_module:
      name: Ticket

ProblemCategory:
  Access admin ticket problem category information:
    actions:
      - problem_and_category
      - delete_problem_category
    system_module:
      name: Ticket

AdditionalCharge:
  Access admin additional charge information:
    actions:
      - additional_charge
      - delete_admin_additional_charge
    system_module:
      name: Ticket

DispatchMethod:
  Access admin dispatch method information:
    actions:
      - dispatch_method
      - delete_dispatch_method
    system_module:
      name: Ticket

PaymentItem:
  Access admin payment item information:
    actions:
      - payment_item
      - delete_admin_payment_item
    system_module:
      name: Ticket

PaymentTerm:
  Access admin payment term information:
    actions:
      - payment_term
      - delete_payment_term
    system_module:
      name: Ticket

Tax:
  Access admin tax information:
    actions:
      - tax
      - delete_tax
      - delete_tax_rate
    system_module:
      name: Ticket

Documents::BrandDocument:
  Access admin annexture information:
    actions:
      - annexture
    system_module:
      name: Contract

OrganizationBankDetail:
  Access Organization Bank Details information:
    actions:
      - create_bank_detail
      - update_organization_bank_detail
      - delete_organization_bank_detail
    system_module:
      name: Ticket

OrganizationContactPerson:
  Access Contact Person information:
    actions:
      - create_organization_contact_person
      - update_organization_contact_person
    system_module:
      name: Organization

ProductBrand:
  Access admin brand information:
    actions:
      - inventory_brand
      - delete_inventory_brand
    system_module:
      name: Ticket

InventoryCategory1:
  Access admin inventory brand information:
    actions:
      - inventory_brand
      - delete_inventory_brand
      - delete_admin_brands_and_category
    system_module:
      name: Inventory

InventoryCategory2:
  Access admin inventory product meta information:
    actions:
      - inventory_product_category
      - delete_inventory_product_category
    system_module:
      name: Inventory

InventoryCategory3:
  Access admin inventory category information:
    actions:
      - category
      - delete_inventory_category
      - delete_admin_brands_and_category
    system_module:
      name: Inventory

InventoryDisposalMethod:
  Access admin inventory disposal method information:
    actions:
      - disposal_method
      - delete_disposal_method
    system_module:
      name: Inventory

InventoryRack:
  Access admin inventory location information:
    actions:
      - location
      - delete_location_rack
      - delete_location_shelf
      - delete_location_bin
    system_module:
      name: Inventory

Manufacture:
  Access admin inventory manufacture information:
    actions:
      - manufacture
      - delete_manufacture
      - delete_inventory_manufacture
    system_module:
      name: Inventory

ProductCondition:
  Access admin inventory product condition information:
    actions:
      - product_condition
      - delete_product_condition
    system_module:
      name: Inventory

InventoryProduct:
  Access admin inventory product information:
    actions:
      - product
      - delete_inventory_product_form
    system_module:
      name: Inventory

  Access inventory information:
    actions:
      - inventories
    system_module:
      name: Inventory

InventoryUnit:
  Access admin inventory unit information:
    actions:
      - unit
      - delete_inventory_unit
    system_module:
      name: Inventory

Inventory:
  Access admin inventory information:
    actions:
      - inventory
    system_module:
      name: Inventory

InventoryReason:
  Access admin inventory reason information:
    actions:
      - reason
      - delete_admin_inventory_reason
    system_module:
      name: Inventory

Ticket:
  Add new ticket:
    actions:
      - set_ticket
      - new
      - find_by_serial
      - create
      - finalize_ticket_save
    system_module:
      name: Ticket

  Assign ticket:
    actions:
      - assign_ticket
      - update_assign_ticket
    system_module:
      name: Ticket

  Access Customer inquire:
    actions:
      - customer_inquire
    system_module:
      name: Ticket

  Access Customer advance payment:
    actions:
      - customer_advance_payment
    system_module:
      name: Ticket

  Access contract-ticket report:
    actions:
      - contract_ticket_report
    system_module:
      name: Contract

  Generate ERP Report:
    actions:
      - excel_output
    system_module:
      name: Ticket

SoPo:
  Create PO:
    actions:
      - create_po
    system_module:
      name: Ticket
  View PO:
    actions:
      - view_po
      - hp_po
    system_module:
      name: Ticket
  Create invoice for HP:
    actions:
      - create_invoice_for_hp
      - js_call_invoice_for_hp
      - js_call_invoice_item
      - js_call_view_more_inv_so
      - create_invoice_for_so
    system_module:
      name: Ticket

ContractProduct:
  Contract cost analytics report:
    actions:
      - contract_cost_analys_report
    system_module:
      name: Contract

TicketContract:
  Generate documents in contract:
    actions:
      - generate_contract_document
      - upload_generated_document
      - remove_generated_document
    system_module:
      name: Contract

  Access Contract Report:
    actions:
      - contract_report
    system_module:
      name: Contract

  Access customer contract:
    actions:
      - index
    system_module:
      name: Contract

  Generate Summary report:
    actions:
      - summery
    system_module:
      name: Contract

ReturnPartsBundle:
  View delivered bundle:
    actions:
      - view_delivered_bundle
    system_module:
      name: Ticket

Gin:
  Search GIN, SRN:
    actions:
      - search_issues
    system_module:
      name: Inventory

Grn:
  Search GIN, SRN:
    actions:
      - search_receives
    system_module:
      name: Inventory

User:
  Search GIN, SRN:
    actions:
      - search_receives
    system_module:
      name: User
  Modify user profile:
    actions:
      - assign_role
      - new
      - profile
      - create
      - update
      - initiate_user_profile_edit
      - upload_avatar
      - assign_role
    system_module:
      name: User