Organization:
  View organizations:
    actions:
      - index
      - show

  Modify organization:
    actions:
      - new
      - edit
      - update
      - destroy
      - temp_save_user_profile_image
      - relate
      - demote_as_department
      - remove_department_org
      - option_for_vat_number
      - pin_relation

  # View parent organization:
  #   actions:
  #     - asdf
  # Modify parent organization:
  #   actions:
  #     - asdf
  Assign dealer type:
    actions:
      - dealer_types
    attributes:
      []
  Modify customer contact details:
    actions:
      - inline_customer_contact_detail
    attributes:
      []
  Access customer product:
    actions:
      - customer_search

  Add/Edit customer contract:
    actions:
      - save

  view customer contract:
    actions:
      - view

  Create GRN:
    actions:
      - grn
      - upload_grn_file
      - initiate_grn_for_i_product
      - initialize_grn
      - initiate_grn_for_srr
      - create_grn
      - search_grn

  Update GRN Cost:
    actions:
      - update_grn_cost

  View part of main cost:
    actions:
      - create_grn_for_main_part

  Create GRN main part:
    actions:
      - grn_main_part
      - create_grn_for_main_part

  Create SRN:
    actions:
      - srn
      - create_srn

  Close SRN:
    actions:
      - close_srn

  Create SRR:
    actions:
      - srr
      - create_srr

  Create GIN:
    actions:
      - gin
      - gins
      - create_gin

  Create PO:
    actions:
      - po
      - pos
      - create_po
  Close PO:
    actions:
      - close_po

  Create PRN:
    actions:
      - prn
      - prns
      - create_prn
      - view_prn

  Close PRN:
    actions:
      - close_prn

  Access admin stores and branches:
    actions:
      - store_and_branch

ProductSoldCountry:
  Access admin country information:
    actions:
      - country
      - delete_admin_country

RegionalSupportCenter:
  Access admin regional information:
    actions:
      - regional_support_center
      - delete_admin_regional_support_center

SlaTime:
  Access admin SLA information:
    actions:
      - sla
      - delete_admin_sla

  Access admin permission information:

IndustryType:
  Access admin industry type information:
    actions:
      - industry_type
      - delete_admin_industry_type
    attributes:
      []

Sbu:
  Access admin sbu information:
    actions:
      - sbu
      - delete_admin_sbu
      - delete_admin_sbu_engineer
    attributes:
      []

MstTitle:
  Access admin mst_title information:
    actions:
      - title
      - delete_admin_title

SparePartDescription:
  Access admin spare part information:
    actions:
      - spare_part_description
  Access Brand & Category information:
    actions:
      - brands_and_category
      - delete_admin_brands_and_category

Reason:
  Access admin reason information:
    actions:
      - reason
      - delete_admin_inventory_reason

Accessory:
  Access admin accessory information:
    actions:
      - accessories
      - delete_admin_accessory

GeQAndA:
  Access admin general question information:
    actions:
      - general_question
      - delete_admin_general_question

Feedback:
  Access admin customer feedback information:
    actions:
      - customer_feedback
      - delete_admin_customer_feedback

TicketStartAction:
  Access admin ticket start action information:
    actions:
      - start_action
      - delete_admin_ticket_start_action

ProblemCategory:
  Access admin ticket problem category information:
    actions:
      - problem_and_category
      - delete_problem_category

AdditionalCharge:
  Access admin additional charge information:
    actions:
      - additional_charge
      - delete_admin_additional_charge

DispatchMethod:
  Access admin dispatch method information:
    actions:
      - dispatch_method
      - delete_dispatch_method

PaymentItem:
  Access admin payment item information:
    actions:
      - payment_item
      - delete_admin_payment_item

PaymentTerm:
  Access admin payment term information:
    actions:
      - payment_term
      - delete_payment_term

Tax:
  Access admin tax information:
    actions:
      - tax
      - delete_tax
      - delete_tax_rate

Documents::BrandDocument:
  Access admin annexture information:
    actions:
      - annexture

OrganizationBankDetail:
  Access Organization Bank Details information:
    actions:
      - create_bank_detail
      - update_organization_bank_detail
      - delete_organization_bank_detail

OrganizationContactPerson:
  Access Contact Person information:
    actions:
      - create_organization_contact_person
      - update_organization_contact_person

ProductBrand:
  Access admin brand information:
    actions:
      - inventory_brand
      - delete_inventory_brand

InventoryCategory1:
  Access admin inventory brand information:
    actions:
      - inventory_brand
      - delete_inventory_brand
      - delete_admin_brands_and_category

InventoryCategory2:
  Access admin inventory product meta information:
    actions:
      - inventory_product_category
      - delete_inventory_product_category

InventoryCategory3:
  Access admin inventory category information:
    actions:
      - category
      - delete_inventory_category
      - delete_admin_brands_and_category

InventoryDisposalMethod:
  Access admin inventory disposal method information:
    actions:
      - disposal_method
      - delete_disposal_method

InventoryRack:
  Access admin inventory location information:
    actions:
      - location
      - delete_location_rack
      - delete_location_shelf
      - delete_location_bin

Manufacture:
  Access admin inventory manufacture information:
    actions:
      - manufacture
      - delete_manufacture
      - delete_inventory_manufacture

ProductCondition:
  Access admin inventory product condition information:
    actions:
      - product_condition
      - delete_product_condition

InventoryProduct:
  Access admin inventory product information:
    actions:
      - product
      - delete_inventory_product_form

  Access inventory information:
    actions:
      - inventories

InventoryUnit:
  Access admin inventory unit information:
    actions:
      - unit
      - delete_inventory_unit

Inventory:
  Access admin inventory information:
    actions:
      - inventory

InventoryReason:
  Access admin inventory reason information:
    actions:
      - reason
      - delete_admin_inventory_reason

Ticket:
  Add new ticket:
    actions:
      - set_ticket
      - new
      - find_by_serial
      - create
      - finalize_ticket_save

  Assign ticket:
    actions:
      - assign_ticket
      - update_assign_ticket

  Access Customer inquire:
    actions:
      - customer_inquire

  Access Customer advance payment:
    actions:
      - customer_advance_payment

  Access contract-ticket report:
    actions:
      - contract_ticket_report

  Generate ERP Report:
    actions:
      - excel_output

SoPo:
  Create PO:
    actions:
      - create_po
  View PO:
    actions:
      - view_po
      - hp_po
  Create invoice for HP:
    actions:
      - create_invoice_for_hp
      - js_call_invoice_for_hp
      - js_call_invoice_item
      - js_call_view_more_inv_so
      - create_invoice_for_so

ContractProduct:
  Contract cost analytics report:
    actions:
      - contract_cost_analys_report

TicketContract:
  Generate documents in contract:
    actions:
      - generate_contract_document
      - upload_generated_document
      - remove_generated_document

  Access Contract Report:
    actions:
      - contract_report

  Access customer contract:
    actions:
      - index

  Generate Summary report:
    actions:
      - summery

ReturnPartsBundle:
  View delivered bundle:
    actions:
      - view_delivered_bundle 