# In spt_ticket table, priority column
priority:
  Highest: 1
  High: 2
  Normal: 3
  Low: 4
  Lowest: 5

ticket_no_format: "T00000"
fsr_no_format: "F00000"
receipt_no_format: "000000"
invoice_no_format: "000000"
quotation_no_format: "Q0000000000"
inventory_serial_no_format: "000000"
inventory_srn_no_format: "000000"
inventory_grn_no_format: "000000"
inventory_gin_no_format: "000000"
inventory_prn_no_format: "000000"
inventory_po_no_format: "000000"
inventory_srr_no_format: "000000"

answer_type_for_q_and_a:
  "yes/no" : "YN"
  text: TX

pagination:
  customer_per_page: 2
  organization_per_page: 2

long_date_format: "%d-%b-%Y"
short_date_format: "%d-%m-%Y"
time_format: "%H:%M"

printer_url: "http://127.0.0.1:1963/"
# non_secured: "http://127.0.0.1:1963"
# secured: "https://print.doc.lk:1967"

icon: ["icon-folder-open","icon-user-tie","icon-hour-glass","icon-bug","icon-bar-graph-2","icon-speech-bubble","icon-open","icon-download","icon-warning"]

Ticket:
  warranty_type_id: 4
  ticket_type_id: 2

TicketSparePart:
  faulty_serial_no: ""
  faulty_ct_no: ""
  received_part_serial_no: ""
  received_part_ct_no: ""
  control_visible_store_request_from_radio: true
  manufacture_label: ""

TicketSparePartManufacture:
  event_no: ""
  order_no: ""

TicketPaymentReceivedType:
  cash: 2
  cheque: 3
  credit card: 4
  draft: 5
  TT_payment: 6
  other: 1

request_part_default: "M"

upload_url: "/inovacrm/production/uploads"

spt_part_quotation_pdf: "vsis"

contact_type_values_map:
  1: 1
  2: 2
  3: 4
  4: 3
  5: 3
  6: 2

spt_quotation_no_annual_reset: true

contract_product_required: false