$ ->
  Organizations.setup()
  Addresses.setup()
  Users.setup()
  RolesAndPermissions.setup()
  DocumentAttachment.setup()
  Tickets.setup()
  Departments.setup()
  Inventories.setup()
  Admins.setup()
  Warranties.setup()
  Lives.setup()
  Invoices.setup()
  Searches.setup()
  Todos.setup()
  Reports.setup()
  Contracts.setup()
  return